//go:build arm64

// Code generated by wasm2go (gcasm backend). DO NOT EDIT.

package stub

import (
	"unsafe"
)

var _ = unsafe.Pointer(nil)

func fn10(m *Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int32)
func fn11(m *Module, l0 int32, l1 int32, l2 int32, l3 int32)
func fn12(m *Module, l0 int32, l1 int32)
func fn13(m *Module)
func fn14(m *Module, l0 int32, l1 int32)
func fn15(m *Module, l0 int32, l1 int32, l2 int32)
func fn16(m *Module, l0 int32, l1 int32, l2 int32, l3 int32)
func fn17(m *Module, l0 int32) (r0 int32)
func fn18(m *Module, l0 int32, l1 int32, l2 int32, l3 int32) (r0 int32)
func fn19(m *Module, l0 int32)
func fn20(m *Module, l0 int32, l1 int32)
func fn21(m *Module, l0 int32, l1 int32) (r0 int32)
func fn22(m *Module, l0 int64) (r0 int64)
func fn23(m *Module)
func fn7(m *Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int32)
func fn8(m *Module, l0 int32, l1 int32, l2 int32, l3 int32, l4 int32)
func fn9(m *Module, l0 int32, l1 int32, l2 int32, l3 int32)

//go:noinline
func gcasmTrapBounds() { panic("wasm: out of bounds access") }

//go:noinline
func gcasmTrapIndirectSig() { panic("wasm: indirect call type mismatch") }

//go:noinline
func gcasmTrapDivZero() { panic("wasm: integer divide by zero") }

//go:noinline
func gcasmTrapOverflow() { panic("wasm: integer overflow") }

//go:noinline
func gcasmTrapUnreachable() { panic("wasm: unreachable") }

var (
	_ = gcasmTrapBounds
	_ = gcasmTrapIndirectSig
	_ = gcasmTrapDivZero
	_ = gcasmTrapOverflow
	_ = gcasmTrapUnreachable
)
