//go:build arm64

// Code generated by wasm2go (gcasm backend). DO NOT EDIT.
//
// Import calls live in assembly, invisible to the linker's
// method pruning, which would fill every itab slot with
// runtime.unreachableMethod. init() is always reachable, so
// the never-taken calls below emit genuine interface call
// sites that pin each method. gcasmKeepAlive is never set.

package stub

var gcasmKeepAlive bool

func init() {
	if !gcasmKeepAlive {
		return
	}
	(HanzoImports)(nil).Hz_close(nil, 0)
	(HanzoImports)(nil).Hz_end(nil, 0, 0, 0)
	(HanzoImports)(nil).Hz_head(nil, 0, 0, 0)
	(HanzoImports)(nil).Hz_open(nil, 0, 0, 0, 0, 0)
	(HanzoImports)(nil).Hz_read(nil, 0, 0, 0)
	(HanzoImports)(nil).Hz_reply(nil, 0, 0, 0)
	(HanzoImports)(nil).Hz_write(nil, 0, 0, 0)
}
