// Copyright 2023-2025 Hanzo AI Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Persona is the personality a caller can give an agent: five-factor scores, a
// voice, and the prose that makes a model answer as someone in particular.
//
// Personas come from two places and read as one list. The catalogue is the
// hanzoai/personas dataset compiled into this binary (personadata/personas.json,
// regenerated by `go generate ./object`); it is the same for every caller and is
// never written. A saved persona is a row, scoped to one user, and a saved
// persona shadows a catalogue entry of the same name — so editing a stock
// persona means saving your own under its name, and deleting yours uncovers the
// original again. That is why there is no seeding step and no migration when the
// dataset grows: the catalogue is data in the binary, not rows in a table.
//
// SECURITY INVARIANT: every accessor is scoped by BOTH owner (org) and userId,
// supplied by the controller from the identity this process verified, never from
// the request body. The primary key is (owner, name) and userId is a separate
// column that single-row lookups also match, so a caller in the same org cannot
// read another user's persona by guessing its name.
package object

import (
	"database/sql/driver"
	"fmt"
	"sort"
	"strings"

	"github.com/hanzoai/ai/util"
	"github.com/hanzoai/dbx"
)

// Persona sources. A caller sees which of the two a persona came from so a UI
// can mark the stock ones and offer "reset" where a save has shadowed one.
const (
	PersonaSourceCatalog = "catalog"
	PersonaSourceUser    = "user"
)

// Ocean carries the five factors on the dataset's 0-100 scale.
type Ocean struct {
	Openness          int `json:"openness"`
	Conscientiousness int `json:"conscientiousness"`
	Extraversion      int `json:"extraversion"`
	Agreeableness     int `json:"agreeableness"`
	Neuroticism       int `json:"neuroticism"`
}

func (o *Ocean) Scan(src interface{}) error  { return JSONScan(o, src) }
func (o Ocean) Value() (driver.Value, error) { return JSONValue(o) }

// clamp holds every factor inside 0-100 so a saved persona cannot carry a score
// the scale does not define.
func (o *Ocean) clamp() {
	for _, f := range []*int{&o.Openness, &o.Conscientiousness, &o.Extraversion, &o.Agreeableness, &o.Neuroticism} {
		if *f < 0 {
			*f = 0
		} else if *f > 100 {
			*f = 100
		}
	}
}

// PersonaTools is what the persona reaches for: essential is what it cannot work
// without, preferred is what it favours, domains are the subjects it speaks to.
type PersonaTools struct {
	Essential []string `json:"essential"`
	Preferred []string `json:"preferred"`
	Domains   []string `json:"domains"`
}

func (t *PersonaTools) Scan(src interface{}) error  { return JSONScan(t, src) }
func (t PersonaTools) Value() (driver.Value, error) { return JSONValue(t) }

// Persona is one personality. Owner+Name is the primary key; UserId is the
// per-user scoping column (column name "user_id" — never "user", which is
// reserved in Postgres).
type Persona struct {
	Owner       string `db:"pk" json:"owner"`
	Name        string `db:"pk" json:"name"`
	UserId      string `json:"userId"`
	CreatedTime string `json:"createdTime"`
	UpdatedTime string `json:"updatedTime"`

	DisplayName   string       `json:"displayName"`
	Category      string       `json:"category"`
	Description   string       `json:"description"`
	Philosophy    string       `json:"philosophy"`
	Ocean         Ocean        `json:"ocean"`
	Tools         PersonaTools `json:"tools"`
	Contributions StringSlice  `json:"contributions"`
	Quotes        StringSlice  `json:"quotes"`
	Prompt        string       `json:"prompt"`

	// Source is derived, not stored: rows are always "user", catalogue entries
	// are always "catalog".
	Source string `db:"-" json:"source"`
}

// GetId returns the owner/name identifier.
func (p *Persona) GetId() string {
	return fmt.Sprintf("%s/%s", p.Owner, p.Name)
}

// System returns the text to send as the system turn. A persona written by hand
// carries its own prose and that wins; otherwise one is composed from the fields
// the dataset does fill in, so a persona with nothing but scores still speaks in
// character rather than silently behaving like no persona at all.
func (p *Persona) System() string {
	if s := strings.TrimSpace(p.Prompt); s != "" {
		return s
	}
	var b strings.Builder
	name := p.DisplayName
	if name == "" {
		name = p.Name
	}
	fmt.Fprintf(&b, "You are %s.", name)
	if p.Description != "" {
		fmt.Fprintf(&b, " %s.", strings.TrimRight(p.Description, "."))
	}
	b.WriteString("\n\nAnswer as this person would: in their voice, from their body of work, with the judgement they were known for. Where you do not know what they held, reason from what they did and say that is what you are doing. Never break character to describe the character.")
	if p.Philosophy != "" {
		fmt.Fprintf(&b, "\n\nWhat you live by: %s", p.Philosophy)
	}
	if len(p.Tools.Domains) > 0 {
		fmt.Fprintf(&b, "\n\nYou speak with authority on: %s.", strings.Join(p.Tools.Domains, ", "))
	}
	if len(p.Contributions) > 0 {
		fmt.Fprintf(&b, "\n\nYour work includes: %s.", strings.Join(p.Contributions, "; "))
	}
	if len(p.Quotes) > 0 {
		b.WriteString("\n\nThings you have said:")
		for _, q := range p.Quotes {
			fmt.Fprintf(&b, "\n  \"%s\"", q)
		}
	}
	fmt.Fprintf(&b, "\n\nYour disposition, on a 0-100 five-factor scale: openness %d, conscientiousness %d, extraversion %d, agreeableness %d, neuroticism %d. Let that shape how you say things — how much you speculate, how much you hedge, how warm you are — not what you claim to be.",
		p.Ocean.Openness, p.Ocean.Conscientiousness, p.Ocean.Extraversion,
		p.Ocean.Agreeableness, p.Ocean.Neuroticism)
	return b.String()
}

// normalize trims the fields a caller controls and holds them inside their
// limits, so one bad save cannot produce a persona the rest of the system has to
// defend against.
func (p *Persona) normalize() {
	p.Name = strings.TrimSpace(p.Name)
	p.DisplayName = strings.TrimSpace(p.DisplayName)
	p.Category = strings.TrimSpace(p.Category)
	p.Description = strings.TrimSpace(p.Description)
	p.Philosophy = strings.TrimSpace(p.Philosophy)
	p.Prompt = strings.TrimSpace(p.Prompt)
	if p.DisplayName == "" {
		p.DisplayName = p.Name
	}
	if p.Category == "" {
		p.Category = "custom"
	}
	p.Ocean.clamp()
	p.Contributions = trimList(p.Contributions)
	p.Quotes = trimList(p.Quotes)
	p.Tools.Essential = trimList(p.Tools.Essential)
	p.Tools.Preferred = trimList(p.Tools.Preferred)
	p.Tools.Domains = trimList(p.Tools.Domains)
}

func trimList(in []string) []string {
	out := make([]string, 0, len(in))
	for _, s := range in {
		if s = strings.TrimSpace(s); s != "" {
			out = append(out, s)
		}
	}
	return out
}

// ValidPersonaName reports whether a name is usable as an addressable slug. The
// same shape the catalogue uses: lowercase letters, digits, hyphen, underscore.
// It is the id in a URL and an @mention, so anything else is rejected at save
// rather than escaped at every point of use.
func ValidPersonaName(name string) bool {
	if len(name) == 0 || len(name) > 128 {
		return false
	}
	for _, r := range name {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9', r == '-', r == '_':
		default:
			return false
		}
	}
	return true
}

func personaScope(owner, userId string) dbx.HashExp {
	return dbx.HashExp{"owner": owner, "user_id": userId}
}

// savedPersonas returns the caller's own personas, newest first.
func savedPersonas(owner, userId string) ([]*Persona, error) {
	personas := []*Persona{}
	if owner == "" || userId == "" {
		return personas, nil
	}
	if err := findAll(adapter.db, "persona", &personas, personaScope(owner, userId), "created_time DESC"); err != nil {
		return personas, err
	}
	for _, p := range personas {
		p.Source = PersonaSourceUser
	}
	return personas, nil
}

// GetPersonas returns everything the caller can address: the catalogue, with
// their own saved personas replacing any catalogue entry of the same name and
// sorted in with the rest by display name.
func GetPersonas(owner, userId string) ([]*Persona, error) {
	saved, err := savedPersonas(owner, userId)
	if err != nil {
		return nil, err
	}
	shadowed := make(map[string]bool, len(saved))
	for _, p := range saved {
		shadowed[p.Name] = true
	}
	out := make([]*Persona, 0, CatalogSize()+len(saved))
	out = append(out, saved...)
	for _, p := range CatalogPersonas() {
		if !shadowed[p.Name] {
			out = append(out, p)
		}
	}
	sort.SliceStable(out, func(i, j int) bool {
		return strings.ToLower(out[i].DisplayName) < strings.ToLower(out[j].DisplayName)
	})
	return out, nil
}

// GetPersona resolves one name for the caller: their own if they saved one under
// it, otherwise the catalogue entry. Returns nil when neither exists.
func GetPersona(owner, userId, name string) (*Persona, error) {
	name = strings.TrimSpace(name)
	if name == "" {
		return nil, nil
	}
	if owner != "" && userId != "" {
		// The primary key is (owner, name); user_id is in the where-clause too so
		// a caller in the same org cannot read another user's persona by name.
		persona := Persona{}
		found, err := getOne(adapter.db, "persona", &persona,
			dbx.HashExp{"owner": owner, "name": name, "user_id": userId})
		if err != nil {
			return nil, err
		}
		if found {
			persona.Source = PersonaSourceUser
			return &persona, nil
		}
	}
	return CatalogPersona(name), nil
}

// SavePersona writes the caller's own persona, creating it or replacing the one
// already stored under that name. Owner and userId must already be set from the
// verified identity; this function never reads them from anywhere else.
func SavePersona(persona *Persona) error {
	persona.normalize()
	if persona.Owner == "" || persona.UserId == "" {
		return fmt.Errorf("persona: owner and user are required")
	}
	if !ValidPersonaName(persona.Name) {
		return fmt.Errorf("persona: name must be lowercase letters, digits, hyphen or underscore")
	}
	existing := Persona{}
	found, err := getOne(adapter.db, "persona", &existing,
		dbx.HashExp{"owner": persona.Owner, "name": persona.Name})
	if err != nil {
		return err
	}
	now := util.GetCurrentTime()
	if found {
		// Owner+Name is the key, so a name another user in the same org already
		// took is refused rather than silently overwritten.
		if existing.UserId != persona.UserId {
			return fmt.Errorf("persona: name already taken")
		}
		persona.CreatedTime = existing.CreatedTime
		persona.UpdatedTime = now
		return adapter.db.Model(persona).Update()
	}
	persona.CreatedTime = now
	persona.UpdatedTime = now
	return insertRow(adapter.db, persona)
}

// DeletePersona removes the caller's own persona. Deleting one that shadowed a
// catalogue entry uncovers the catalogue entry again. Catalogue entries
// themselves cannot be deleted — they are data in the binary, not rows.
func DeletePersona(owner, userId, name string) (bool, error) {
	if owner == "" || userId == "" || strings.TrimSpace(name) == "" {
		return false, nil
	}
	// user_id is in the where-clause, so a caller can only ever delete their own.
	affected, err := deleteWhere(adapter.db, "persona",
		dbx.HashExp{"owner": owner, "name": strings.TrimSpace(name), "user_id": userId})
	if err != nil {
		return false, err
	}
	return affected != 0, nil
}
